[package]
name = "blackjack"
type = "contract"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.0", directory = "noir-projects/aztec-nr/aztec" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.0", directory = "noir-projects/aztec-nr/value-note" }
address_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.0", directory = "noir-projects/aztec-nr/address-note" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.0", directory = "noir-projects/noir-contracts/contracts/token_contract" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.0", directory = "noir-projects/aztec-nr/uint-note" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.0", directory = "noir-projects/aztec-nr/authwit" }
